export const workspaceRoutes = {
  analytics: "/analytics",
  carriers: "/carriers",
  compliance: "/compliance",
  dashboard: "/dashboard",
  documents: "/documents",
  exceptions: "/exceptions",
  fieldOps: "/field-ops",
  intelligence: "/intelligence",
  integrations: "/integrations",
  imports: "/imports",
  invoices: "/invoices",
  logistics: "/logistics",
  onboarding: "/onboarding",
  payments: "/payments",
  rates: "/rates",
  reports: "/reports",
  scorecards: "/scorecards",
  settings: "/settings",
  settingsAccess: "/settings/access",
  settingsAlerts: "/settings/alerts",
  settingsAudit: "/settings/audit",
  settingsOrganization: "/settings/organization",
  settingsProfile: "/settings/profile",
  spendAnalysis: "/spend-analysis",
  tracking: "/tracking",
} as const;

export const adminRoutes = {
  root: "/admin",
  audits: "/admin/audits",
  carriers: "/admin/carriers",
  dashboard: "/admin/dashboard",
  exceptions: "/admin/exceptions",
  export: "/admin/export",
  login: "/admin/login",
  payments: "/admin/payments",
  rates: "/admin/rates",
  reports: "/admin/reports",
  settings: "/admin/settings",
  tracking: "/admin/tracking",
  users: "/admin/users",
} as const;

export const supplyChainManagerRoutes = {
  analytics: workspaceRoutes.analytics,
  carriers: workspaceRoutes.carriers,
  dashboard: workspaceRoutes.dashboard,
  exceptions: workspaceRoutes.exceptions,
  fieldOps: workspaceRoutes.fieldOps,
  intelligence: workspaceRoutes.intelligence,
  integrations: workspaceRoutes.integrations,
  logistics: workspaceRoutes.logistics,
  rates: workspaceRoutes.rates,
  reports: workspaceRoutes.reports,
  scorecards: workspaceRoutes.scorecards,
  settingsAccess: workspaceRoutes.settingsAccess,
  spendAnalysis: workspaceRoutes.spendAnalysis,
  tracking: workspaceRoutes.tracking,
} as const;

export const billingManagerRoutes = {
  dashboard: workspaceRoutes.dashboard,
  documents: workspaceRoutes.documents,
  invoices: workspaceRoutes.invoices,
  payments: workspaceRoutes.payments,
  reports: workspaceRoutes.reports,
  settingsAccess: workspaceRoutes.settingsAccess,
} as const;

export const driversCarriersRoutes = {
  dashboard: workspaceRoutes.dashboard,
  documents: workspaceRoutes.documents,
  exceptions: workspaceRoutes.exceptions,
  fieldOps: workspaceRoutes.fieldOps,
  logistics: workspaceRoutes.logistics,
  tracking: workspaceRoutes.tracking,
} as const;

export const workspaceRoutePrefixes = [
  workspaceRoutes.analytics,
  workspaceRoutes.compliance,
  workspaceRoutes.dashboard,
  workspaceRoutes.settings,
  workspaceRoutes.imports,
  workspaceRoutes.documents,
  workspaceRoutes.carriers,
  workspaceRoutes.integrations,
  workspaceRoutes.intelligence,
  workspaceRoutes.rates,
  workspaceRoutes.reports,
  workspaceRoutes.scorecards,
  workspaceRoutes.spendAnalysis,
  workspaceRoutes.tracking,
  workspaceRoutes.invoices,
  workspaceRoutes.payments,
  workspaceRoutes.fieldOps,
  workspaceRoutes.logistics,
  workspaceRoutes.exceptions,
] as const;
